#    Тут мы можем указать все новые имена маркировок, чтобы при запуске маркированных тестов пайтест не сыпал Warning`и в терминале
[pytest]
markers =
    smoke
    regression
    parametrize
    func

pythonpath = .
