# В этом файле конфигурируем запуск тестов на ГитХабе

# Сейчас делаю дефолтный запуск тестов: тесты будут запускаться при каждом новом пуше изменений
name: Automated tests    # задаём имя файлу

# ниже указываем, в какой ситуации (конструкции) это всё будет отрабатывать
on:    # ON - это конструкция "если..."
  push    # запускается, если произошёл пуш

# ниже описывается сам алгоритм запуска тестов:
jobs:    # JOBS - это задача
  tests:    # задача = запустить тесты
