# В этом файле конфигурируем запуск тестов на ГитХабе

# 1. Сейчас делаю дефолтный запуск тестов: тесты будут запускаться при каждом новом пуше изменений

#name: Automated tests    # задаём имя файлу
## ниже указываем, в какой ситуации (конструкции) это всё будет отрабатывать
#on:    # ON - это конструкция "если..."
#  push    # запускается, если произошёл пуш
## ниже описывается сам алгоритм запуска тестов:
#jobs:    # JOBS - это задача
#  tests:    # задача = запустить тесты
#    runs-on: ubuntu-latest    # указываем ОС, на которой будет запуск тестов
## ниже расписываем шаги, которые нужны для прогона теста
#    steps:    # в этом блоки даём название шагов и пояснение, что должно происходить на этом шаге
#      - name: Checkout repository    # шаг 1: скачиваем код внутрь нашего контейнера
#        uses: actions/checkout@v3    #        пользуемся готовыми/дефолтными шагами из функции "actions" гитхаба + через @ указываем версию функции
#      - name: setup Python    # шаг 2: установить питон
#        uses: actions/setup-python@v4    # обращаемся также к заготовленному экшну: установка пайтона + также через @ указываем последнюю актуальную версию
#        with:    # в этом блоке указываем точные настройки того, что нужно установить
#          python-version: "3.10"    # пишем конкретную версию питона, которую нужно установить
#      - name: Install Chrome    # шаг 3: устанавливаем Хром (самописное действие, не заготовленное)
#        run: sudo apt-get install google-chrome-stable    # эта команда должна будет устанвить последнюю стабильную версию Хрома
#      - name: Install dependencies    # шаг 4: установка всех зависимостей в проект
#        run: pip install -r requirements.txt    # через терминал устанавливаем все необходимые зависимости в проект
#      - name: Run tests    # финальный шаг: Запуск тестов
#        run: pytest

# 2. Делаем кастомный запуск:
name: Automated tests    # задаём имя файлу
# ниже указываем, в какой ситуации (конструкции) это всё будет отрабатывать
on:    # ON - это конструкция "если..."
  workflow_dispatch: # юзаем, если нужны какие-то кастомные настройки для запуска ()
    inputs: # внутри него расписываем, что должно происходить
      deployment_target: # тут описываем команду/цель
        description: Choose target
        required: true # делаем ТРУ, чтобы не было возможности запуска без какой-то опции "что хотим запустить: ждём выбор пользователя, что именно он хочет запустить"
        default: # опция, которая будет воспроизводится по дефолту: можем указать только какие-нибудь смоук-тесты и будут гоняться они
        type: choice # опция: способ выбора - чойс (селектор, из которого мы выбираем опции)
        options: # в этом параметре перечисляем все опции, которые у нас есть
          - first_test
          - second_test
          - all_test
# ниже описывается сам алгоритм запуска тестов:
jobs:    # JOBS - это задача
  tests:    # задача = запустить тесты
    runs-on: ubuntu-latest    # указываем ОС, на которой будет запуск тестов
# ниже расписываем шаги, которые нужны для прогона теста
    steps:    # в этом блоки даём название шагов и пояснение, что должно происходить на этом шаге
      - name: Checkout repository    # шаг 1: скачиваем код внутрь нашего контейнера
        uses: actions/checkout@v3    #        пользуемся готовыми/дефолтными шагами из функции "actions" гитхаба + через @ указываем версию функции
      - name: setup Python    # шаг 2: установить питон
        uses: actions/setup-python@v4    # обращаемся также к заготовленному экшну: установка пайтона + также через @ указываем последнюю актуальную версию
        with:    # в этом блоке указываем точные настройки того, что нужно установить
          python-version: "3.10"    # пишем конкретную версию питона, которую нужно установить
      - name: Install Chrome    # шаг 3: устанавливаем Хром (самописное действие, не заготовленное)
        run: sudo apt-get install google-chrome-stable    # эта команда должна будет устанвить последнюю стабильную версию Хрома
      - name: Install dependencies    # шаг 4: установка всех зависимостей в проект
        run: pip install -r requirements.txt    # через терминал устанавливаем все необходимые зависимости в проект
      - name: first test    # финальный шаг: Запуск тестов: в зависимости от выбора пользователя
        if: "github.event.inputs.deployment_target == 'first_test'" # делаем заглушку/условие, что если выбираем для запуска фёрст_тест, то секонд_тест не запускаются
        run: pytest tests_ui/test_GET_paper_page.py::test_get_paper_page # указываем имя теста, который нужно запустить
      - name: second test    # финальный шаг: Запуск тестов: в зависимости от выбора пользователя
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests_ui/test_POST_correct_authorization.py::test_correct_login # указываем имя теста, который нужно запустить
      - name: all test # запустятся все тесты
        if: "github.event.inputs.deployment_target == 'all_test'"
        run: pytest
