# В этом файле конфигурируем запуск тестов на ГитХабе

# Сейчас делаю дефолтный запуск тестов: тесты будут запускаться при каждом новом пуше изменений

name: Automated tests    # задаём имя файлу
# ниже указываем, в какой ситуации (конструкции) это всё будет отрабатывать
on:    # ON - это конструкция "если..."
  push    # запускается, если произошёл пуш
# ниже описывается сам алгоритм запуска тестов:
jobs:    # JOBS - это задача
  tests:    # задача = запустить тесты
    runs-on: ubuntu-latest    # указываем ОС, на которой будет запуск тестов
# ниже расписываем шаги, которые нужны для прогона теста
    steps:    # в этом блоки даём название шагов и пояснение, что должно происходить на этом шаге
      - name: Checkout repository    # шаг 1: скачиваем код внутрь нашего контейнера
        uses: actions/checkout@v3    #        пользуемся готовыми/дефолтными шагами из функции "actions" гитхаба + через @ указываем версию функции
      - name: setup Python    # шаг 2: установить питон
        uses: actions/setup-python@v4    # обращаемся также к заготовленному экшну: установка пайтона + также через @ указываем последнюю актуальную версию
        with:    # в этом блоке указываем точные настройки того, что нужно установить
          python-version: "3.10"    # пишем конкретную версию питона, которую нужно установить
      - name: Install Chrome    # шаг 3: устанавливаем Хром (самописное действие, не заготовленное)
        run: sudo apt-get install google-chrome-stable    # эта команда должна будет устанвить последнюю стабильную версию Хрома
      - name: Install dependencies    # шаг 4: установка всех зависимостей в проект
        run: pip install -r requirements.txt    # через терминал устанавливаем все необходимые зависимости в проект
      - name: Run tests    # финальный шаг: Запуск тестов
        run: pytest